import { drawImage } from "./canvasDrawing";

export function load_images(){
    let images = "title scene.png|transition.png|coach.png|girl happy 2.png|girl happy.png|girl neutral 2.png|girl neutral.png|girl sad 2.png|girl sad.png|happy2.png|icon.png|instructor.png|mute.png|neutral2.png|ringmaster.png|sad2.png|screen_bg.png|selection.png|unmute.png|icons/board games.png|icons/bowling.png|icons/car.png|icons/circus.png|icons/dancing.png|icons/end.png|icons/escape room.png|icons/garden.png|icons/golf.png|icons/grocery store.png|icons/house.png|icons/library.png|icons/movie.png|icons/museum.png|icons/painting.png|icons/park.png|icons/restaurant.png|icons/rock climbing.png|icons/room.png|icons/scenery.png|icons/selection.png|icons/singing.png|icons/skating.png|icons/video games.png|icons/zoo.png|scenes/board games.png|scenes/bookstore.png|scenes/bowling.png|scenes/car.png|scenes/circus inside.png|scenes/circus.png|scenes/classroom.png|scenes/coach.png|scenes/dancing.png|scenes/end.png|scenes/escape room.png|scenes/garden.png|scenes/golf.png|scenes/house.png|scenes/instructor.png|scenes/karaoke.png|scenes/movie theater.png|scenes/museum inside.png|scenes/museum.png|scenes/painting.png|scenes/park.png|scenes/restaurant.png|scenes/ringmaster.png|scenes/rock climbing.png|scenes/room.png|scenes/selection.png|scenes/skating.png|scenes/stargazing.png|scenes/store.png|scenes/video games.png|scenes/zoo.png|small_scenes/board games.png|small_scenes/bookstore.png|small_scenes/bowling.png|small_scenes/car.png|small_scenes/circus inside.png|small_scenes/circus.png|small_scenes/dancing.png|small_scenes/end.png|small_scenes/escape room.png|small_scenes/garden.png|small_scenes/golf.png|small_scenes/house.png|small_scenes/karaoke.png|small_scenes/movie theater.png|small_scenes/museum inside.png|small_scenes/museum.png|small_scenes/painting.png|small_scenes/park.png|small_scenes/restaurant.png|small_scenes/rock climbing.png|small_scenes/room.png|small_scenes/selection.png|small_scenes/skating.png|small_scenes/stargazing.png|small_scenes/store.png|small_scenes/video games.png|small_scenes/zoo.png|test/bg1.png|test/bg2.png|test/fg1.png|test/fg2.png|test/girl happy 2.png|test/girl happy.png|test/girl neutral 2.png|test/girl neutral.png|test/girl sad 2.png|test/girl sad.png|test/ic1.png|test/ic2.png".split("|");
    let promises :Promise<string>[] = []
    for(let item of images){
        promises.push(drawImage(undefined, item, 0, 0) as Promise<string>); 
    }
    return Promise.allSettled(promises); 
}